[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
exclude = ["lib/openzeppelin-contracts/certora", "lib/openzeppelin-contracts/test", "lib/openzeppelin-contracts/lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
via_ir = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
